--- #YAML:1.0
name:               Dpchrist-File-LimitPath
version:            1.035
abstract:           limit path lengths
author:
    - David Paul Christensen dpchrist@holgerdanske.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:                 0
    Data::Dumper:         0
    Dpchrist::Debug:      1.047
    Dpchrist::ExtUtils::MakeMaker:  1.015
    Exporter:             0
    ExtUtils::MakeMaker:  0
    File::Basename:       0
    File::Copy:           0
    File::Find:           0
    File::Path:           0
    File::Slurp:          0
    Getopt::Long:         0
    Pod::Usage:           0
    Test::Compile:        0
    Test::Manifest:       0
    Test::More:           0
    Test::Pod:            0
    Test::Prereq:         0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
